command_timeout=5000

[character]
format="$symbol "
# tux goes brrr
success_symbol="[](bold green)"
error_symbol="[](bold red)"
vimcmd_symbol="[](bold green)"
vimcmd_replace_one_symbol="[](bold green)"
vimcmd_replace_symbol="[](bold green)"
vimcmd_visual_symbol="[](bold green)"
# vimcmd_symbol="[](bold blue)"
# vimcmd_replace_one_symbol="[](bold cyan)"
# vimcmd_replace_symbol="[](bold cyan)"
# vimcmd_visual_symbol="[](bold lightgray)"
disabled=false

[cmake]
format="[$symbol($version )]($style)"
version_format=" ${raw}"
symbol="cmake"
detect_extensions=[]
detect_files=["CMakeLists.txt", "CMakeCache.txt"]
detect_folders=[]
style="bold blue"
disabled=true

[cmd_duration]
min_time=5000
show_milliseconds=false
format="[ $duration]($style) "
style="bold yellow"
disabled=false

[directory]
truncation_length=2
truncate_to_repo=false
format="[$path]($style)[$read_only]($read_only_style) "
disabled=false
read_only=""
read_only_style="red"
truncation_symbol="../"
#repo_root_style=
repo_root_format="[$before_root_path]($style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
home_symbol="~"
use_os_path_sep=true

[line_break]
disabled=false

[git_branch]
always_show_remote=false
format="[$symbol$branch]($style) "
symbol=""
style="bold purple"
#truncation_length=2^63 - 1
truncation_symbol="..."
only_attached=false
ignore_branches=[]
disabled=false

[git_commit]
commit_hash_length=7
format="[\\($hash$tag\\)]($style) "
style="bold green"
only_detached=false
tag_disabled=false
tag_symbol="󰓹"
disabled=false

[git_state]
rebase="rebasing"
merge="merging"
revert="reverting"
cherry_pick="cherry-picking"
bisect="bisecting"
am="am"
am_or_rebase="am/rebase"
style="bold yellow"
# format="[\($state( $progress_current/$progress_total)\)]($style) "
disabled=false

[git_metrics]
added_style="green"
deleted_style="red"
only_nonzero_diffs=true
format="([+$added]($added_style) )([-$deleted]($deleted_style) )"
disabled=false

[git_status]
format='([$all_status$ahead_behind]($style) )'
style="bold green"
conflicted=""
ahead=""
behind=""
diverged=""
up_to_date=""
untracked=""
stashed=""
modified=""
staged=""
renamed=""
deleted=""
